@host = http://localhost:4000/api
@randomId = {{ $randomInt 1 999999 }}

### ===================================================================================

### Create Trainer
# @name createTrainer
@trainerId = {{ createTrainer.response.body.trainer.id }}
POST {{host}}/trainers
Content-Type: application/json

{
  "name": "Trainer Teste {{randomId}} (REST Client)",
  "password": "123456"
}

### Sign In Trainer
# @name sign_in_trainer
@token = {{ sign_in_trainer.response.body.token }}
POST {{host}}/trainers/signin
Content-Type: application/json

{
  "id": "{{trainerId}}",
  "password": "123456"
}

### Get Trainer
# @name getTrainer
GET {{host}}/trainers/{{trainerId}}
Authorization: Bearer {{token}}

### Update Trainer
# @name updateTrainer
PUT {{host}}/trainers/{{trainerId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Trainer Updated {{randomId}} (REST Client)",
  "password": "123456"
}

### Update Trainer
# @name updateTrainer
PATCH {{host}}/trainers/{{trainerId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Trainer Updated {{randomId}} (REST Client)",
  "password": "123456"
}

### Delete Trainer
# @name deleteTrainer
DELETE {{host}}/trainers/{{trainerId}}
Authorization: Bearer {{token}}

### ============================================================================

### Create Trainer Pokemon
# @name createTrainerPokemon
@pokemon_id = {{ createTrainerPokemon.response.body.pokemon.id }}
POST {{host}}/trainer_pokemons
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "pikachu",
  "nickname": "boca loka",
  "trainer_id": "{{trainerId}}"
}

### Get Pokemon Trainer
# @name getPokemonTrainer
GET {{host}}/trainer_pokemons/{{pokemon_id}}
Authorization: Bearer {{token}}

### Update Pokemon Trainer
# @name updatePokemonTrainer
PUT {{host}}/trainer_pokemons/{{pokemon_id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nickname": "Pokemon updated PUT"
}

### Update Pokemon Trainer
# @name updatePokemonTrainer
PATCH {{host}}/trainer_pokemons/{{pokemon_id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nickname": "Pokemon updated PATCH"
}

### Delete Trainer
# @name deleteTrainer
DELETE {{host}}/trainer_pokemons/{{pokemon_id}}
Authorization: Bearer {{token}}

### ============================================================================

### Get Pokemon
# @name getPokemon
GET {{host}}/pokemons/pikachu